### ISSUE TITLE
wbgdata fails to install on Linux distributions

### ISSUE THREAD

**Issue by Nenuial** [worldbank/wbgviz#36]
Something goes wrong when wbgdata is installed on Linux distributions:

```
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
* installing *source* package ‘wbgdata’ ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
Warning in get_wbcache() :
  Countries/series cache is stale - use refresh_wbcache() to update.
Error: package or namespace load failed for ‘wbgdata’:
 .onLoad failed in loadNamespace() for 'wbgdata', details:
  call: NULL
  error: Can't subset columns that don't exist.
✖ Column `regionID` doesn't exist.
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/usr/local/lib/R/site-library/wbgdata’
```

**Comment by Nenuial** [comment]
Tried fixing it in #37

**Comment by tonyfujs** [comment]
Thanks @Nenuial 
This package was developed to support the creation of the [SDG Atlas 2018](https://blogs.worldbank.org/opendata/2018-atlas-sustainable-development-goals-all-new-visual-guide-data-and-development), and is not actively maintained.

The issue you are experiencing seems to be related to the wbstats package. wbstats v 1.0.1 introduced some breaking changes, and wbgviz has not been updated accordingly.

Using a previous version of wbstats should allow you to use wbgviz without problem.

**Comment by Nenuial** [comment]
Thanks for these infos, I will change my scripts to use wbstats from now on.
